<?php

namespace PortfolioBundle\Repository;

/**
 * ReferentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferentRepository extends \Doctrine\ORM\EntityRepository
{
}
